### PR TITLE
Adds initial cmake setup

### LINKED ISSUE #3: Consider cmake
I was wondering if you guys ever considered using cmake? This would remove the need to maintain all the makefiles and use a single cmakefile instead as most platform-specific stuff is handled by cmake itself or toolchain files.

### PR DESCRIPTION
**Pull request by mjvk**
I made a start on the cmake setup. Have a look and let me know what you think of it. This might also be a good point to add some CI.

Fixes #3

### CODE REVIEW

**Comment by mjvk** [comment]
Was wondering how you guys like this? Think it is good to go?

**Comment by b00ga** [comment]
Currently doesn’t build on FreeBSD, OpenBSD and macOS Mojave. I started getting together a Windows 10 test VM as well, but haven’t reached the ‘try to build’ stage yet.

On the tested platforms mentioned, it’s pulling in Linux specific sources (eg zebraroutemgr which includes the Linux only asm/types.h).

I started looking at the platform conditionals in the waf build (starting here https://github.com/USNavalResearchLaboratory/protolib/blob/93acc1bc002b29cf6ba09118de5d7c65baea18ba/wscript#L88) to compare.

I’m still working full time with some major summer deadlines so I’ve been super busy. So although I’ve wanted to spend time on this, I just haven’t had the free cycles.

**Comment by mjvk** [comment]
I'll try to have a look. Which platform do you want to have supported before completing this PR?

**Comment by b00ga** [comment]
That’s a call for @bebopagogo

I’m not an owner of the repo, just a user with cmake experience and an interest in seeing this done.

**Comment by mjvk** [comment]
Ok tried on:
- QNX
- FreeBSD
- W10 using MSVC 19
- Ubuntu
- Debian

Missing are things like mac, openbsd, solaris, netbsd, rtems, sgi etc. Only tested x86-64 and only building, not consuming.

**Comment by b00ga** [comment]
Tested on (base build only, no optional features, x86_64 only):
* macOS High Sierra
* CentOS 6/7/8
* Fedora 31
* Ubuntu 16.04/18.04
* Debian 10
* openSUSE 15.1
* Arch Linux
* FreeBSD 11/12
* OpenBSD 6.6
* NetBSD 8
* OpenIndiana Hipster

Observations:
* CentOS 6 and 7 only have CMake 2.x. Both have CMake 3.x in the EPEL repository.
* CentOS 6 EPEL only has CMake 3.6
* Ubuntu 16.04 only has CMake 3.5.1
* On both of the above, if I change the minimum from 3.10 to 3.1, I can build successfully. (I find 3.1 is a decent baseline as it supports decent C++11 checks and providing a version number parameter to the project( ) call).
* I noticed on a lot of my vagrant images that I don't have libxml2. CMake complains not found, but it builds anyway. A super quick check didn't seem that anything is building src/common/protoXml.cpp. Did not investigate if this is also a deficiency of makefiles or waf yet.
* macOS and OpenBSD fail to build. See errors below.
* Solaris builds appear broken across the board. Using the OpenSolaris derivative, OpenIndiana, I tried CMake, waf, Makefile.solaris and Makefile.solx86 and none of them compile.

macOS failure:
```
[ 41%] Building CXX object CMakeFiles/protolib.dir/src/common/protoDispatcher.cpp.o
/Users/shawn/projects/vagrant-protolib-cmake/protolib/src/common/protoDispatcher.cpp:868:14: error: use of undeclared
      identifier 'sched_setscheduler'
    if (0 != sched_setscheduler(0, SCHED_FIFO, &schp))
             ^
/Users/shawn/projects/vagrant-protolib-cmake/protolib/src/common/protoDispatcher.cpp:871:18: error: use of undeclared
      identifier 'sched_setscheduler'
        if (0 != sched_setscheduler(0, SCHED_OTHER, &schp))
                 ^
2 errors generated.
make[2]: *** [CMakeFiles/protolib.dir/src/common/protoDispatcher.cpp.o] Error 1
make[1]: *** [CMakeFiles/protolib.dir/all] Error 2
make: *** [all] Error 2
```
OpenBSD failure:
```
[ 35%] Building CXX object CMakeFiles/protolib.dir/src/common/protoDispatcher.cpp.o
/home/vagrant/protolib/src/common/protoDispatcher.cpp:868:14: error: use of undeclared identifier 'sched_setscheduler'
    if (0 != sched_setscheduler(0, SCHED_FIFO, &schp))
             ^
/home/vagrant/protolib/src/common/protoDispatcher.cpp:871:18: error: use of undeclared identifier 'sched_setscheduler'
        if (0 != sched_setscheduler(0, SCHED_OTHER, &schp))
                 ^
2 errors generated.
*** Error 1 in . (CMakeFiles/protolib.dir/build.make:232 'CMakeFiles/protolib.dir/src/common/protoDispatcher.cpp.o': /usr/bin/c++  -DHAVE_AS...)
*** Error 1 in . (CMakeFiles/Makefile2:76 'CMakeFiles/protolib.dir/all')
*** Error 1 in /home/vagrant/protolib/build (Makefile:130 'all')
```

Pretty nice coverage though. I'll try testing with some of the options turned on when I have some more time. I'd like to try 32-bit Linux and cross-compiling for ARM if I have the cycles, but I wouldn't let that block.

@bebopagogo There's a lot of good stuff here. Be nice to get macOS and OpenBSD building, but accepting this PR as side-by-side with Makefiles and waf is probably pretty reasonable at this point. Take further enhancing it from there (and maybe replacing the other builds) as feature enhancements/future PRs from there?

I'm not a developer, just a sysadmin and devops guy, build system nerd, and operating system aficionado. That said, I'm happy to keep testing as I have time.

**Comment by b00ga** [comment]
Tried WX build on Ubuntus and Fedora. Got an error on line 84 of CMakeLists.txt. Updated and wxProtoApp.cpp got included and built. Git diff below.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a256d62..58d6888 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -81,7 +81,7 @@ if(LibXml2_FOUND)
 endif()
 
 if(ENABLE_WX)
-       find_package(wxWidgets core base REQUIRED)
+       find_package(wxWidgets REQUIRED COMPONENTS core base)
        if(wxWidgets_FOUND)
                include(${wxWidgets_USE_FILE})
                list(APPEND PLATFORM_LIBS ${wxWidgets_LIBRARIES})
```

**Comment by mjvk** [comment]
Thanks! Pushed fixes for mac (with the scheduling) and wxwidgets as you suggested.

**Comment by mjvk** [comment]
Ok so I think we are quite far, I added some stuff for libxml. Just wondering if we should make that an option like wxwidgets (I think we should). In addition manetGraphML2 doesn't seem functional right?

**Comment by bebopagogo** [comment]
I will look at it right now.

**Comment by bebopagogo** [comment]
I did a test with your fork to make sure the norm code built.  I will refresh some of my other source trees and make sure all is OK, but from looking at the file changes, I don't think there will be any issues.  I did not test the Cmake stuff but will continue to familiarize myself with that.

**Pull request merged**
