### PR TITLE
pkg-config and PIE fixes

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
https://github.com/USNavalResearchLaboratory/norm/pull/23

**Review by bebopagogo — APPROVED** [review]

**Comment by b00ga** [comment]
Just curious what the reasoning is for changing from CMake native (find_package) to pkg-config for LibXML2? CMake has come with it's own built in find_package module for LibXML2 basically forever.

**Comment by bluca** [comment]
> Just curious what the reasoning is for changing from CMake native (find_package) to pkg-config for LibXML2? CMake has come with it's own built in find_package module for LibXML2 basically forever.

Because pkg-config is a universal standard, while project-specific or buildsystem-specific alternatives are not even close to being as well supported and cover all the required use cases

**Comment by b00ga** [comment]
I know what pkg-config is and how it works. I guess I just don't grok why it is "better" than CMake's built-in native function for the same (in fact you're using that built-in functionality to find _pkg-config_ in the first place).  I've never run into one of these "project-specific or buildsystem-specific" issues with CMake's built-in function, so it seemed like an arbitrary change to me.

I guess this commit is falling back on CMake FindLibXML2 if pkg-config isn't found. However, looking at this commit and the LibXML2 docs (https://cmake.org/cmake/help/latest/module/FindLibXml2.html), CMake's module returns ALL CAPS variables and the pkg-config check uses PascalCase. If this check is going to remain, the pkg_check_modules should use an ALL CAPS var so that the include_directories and addition to PLATFORM_LIBS work in either the pkg-config or find_package methods.

**Pull request merged**
